comictitles = [
    {"title" : "What is this book?", "newchapter": "true", "newsubchapter": "About This Book"}, 
    {"title" : "What is real analysis?", "newsubchapter": "About Real Analysis"}, 
    {"title" : "Why do real analysis?"},
    {"title" : "Why do real analysis books rarely use pictures?"},
    {"title" : "How do you prove that something doesn't exist?", "newchapter": "true", "newsubchapter": "Irrationality"},
    {"title" : "How do you prove non-existence in math?"},
    {"title" : "How do you prove irrationality?"},
    {"title" : "Is the square root of two irrational?"},
    {"title" : "But do irrational numbers actually exist?"},
    {"title" : "How does proving irrationality relate to analysis?"},
    {"title" : "Why does real analysis feel so unrelated to calculus?"},
    {"title" : "How do we know where to put numbers on a number line?", "newsubchapter": "Ordered Sets"},
    {"title" : "Does every set have a biggest number?"},
    {"title" : "Isn't infinity the biggest element in the set {1,2,3...}?"},
    {"title" : "How do you prove infinity isn't an integer?"},
    {"title" : "Does every upper bounded set have a biggest element?"},
    {"title" : "What's the most important upper bound of a set?"},
    {"title" : "Does every upper-bounded set contain its supremum?"},
    {"title" : "What's the most important lower bound of a set?"},
    {"title" : "Does every lower-bounded set contain its infimum?"},
    {"title" : "What's the point of formal definitions?"},
    {"title" : "How can we prove something is an infimum?"},
    {"title" : "What's the point of formal proofs when we have intuition?"},
    {"title" : "Does inf(A) equal -sup(-A)?"},
    {"title" : "What is a number?", "newsubchapter": "Fields"},
    {"title" : "What is a complex number?"},
    {"title" : "What should a universe of numbers look like?"},
    {"title" : "How should we order fields?"},
    {"title" : "Is the complex field an ordered field?"},
    {"title" : "How do we construct the real numbers?", "newsubchapter": "The Real Number Field"},
    {"title" : "Are irrationals a subset of the reals?"},
    {"title" : "Are there infinitesimally small elements in the real line?"},
    {"title" : "How can we raise a number to a negative power?"},
    {"title" : "What happens when we put a bunch of real lines together?"},
    {"title" : "What happens to the reals when we allow dividing by zero?"},
    {"title" : "What's so special about the reals?"},
    {"title" : "Conclusion",  "newsubchapter": "Conclusion"}

];