comictitles = [
    {"title" : "1. What is this book?", "newchapter": "true", "newsubchapter": "About This Book"}, 
    {"title" : "2. What is real analysis?", "newsubchapter": "About Real Analysis"}, 
    {"title" : "3. Why do real analysis?"},
    {"title" : "4. Why do real analysis books rarely use pictures?"},
    {"title" : "5. How do you prove that something doesn't exist?", "newchapter": "true", "newsubchapter": "Irrationality"},
    {"title" : "6. How do you prove non-existence in math?"},
    {"title" : "7. How do you prove irrationality?"},
    {"title" : "8. Is the square root of two irrational?"},
    {"title" : "9. But do irrational numbers actually exist?"},
    {"title" : "10. How does proving irrationality relate to analysis?"},
    {"title" : "11. Why does real analysis feel so unrelated to calculus?"},
    {"title" : "12. How do we know where to put numbers on a number line?", "newsubchapter": "Ordered Sets"},
    {"title" : "13. Does every set have a biggest number?"},
    {"title" : "14. Isn't infinity the biggest element in the set {1,2,3...}?"},
    {"title" : "15. How do you prove infinity isn't an integer?"},
    {"title" : "16. Does every upper bounded set have a biggest element?"},
    {"title" : "17. What's the most important upper bound of a set?"},
    {"title" : "18. Does every upper-bounded set contain its supremum?"},
    {"title" : "19. What's the most important lower bound of a set?"},
    {"title" : "20. Does every lower-bounded set contain its infimum?"},
    {"title" : "21. What's the point of formal definitions?"},
    {"title" : "22. How can we prove something is an infimum?"},
    {"title" : "23. What's the point of formal proofs when we have intuition?"},
    {"title" : "24. Does inf(A) equal -sup(-A)?"},
    {"title" : "25. What is a number?", "newsubchapter": "Fields"},
    {"title" : "26. What is a complex number?"},
    {"title" : "27. What should a universe of numbers look like?"},
    {"title" : "28. How should we order fields?"},
    {"title" : "29. Is the complex field an ordered field?"},
    {"title" : "30. What's so special about the reals?", "newsubchapter": "The Real Number Field"},
    {"title" : "31. How do we construct the real numbers?"}

];